[supabase]
SUPABASE_URL="https://imwocxpyecafurphkqzv.supabase.co"
SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imltd29jeHB5ZWNhZnVycGhrcXp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4ODM1NzksImV4cCI6MjA1NzQ1OTU3OX0.3Yw2D_BzoxEpjeNywpWjTfTh3zuRCdxGInKPitvmvwY"